config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#home'

  # get  '/course/index' => 'course#index'
  resources :course

  # get  '/cohort/index' => 'cohort#index'
  resources :cohort
  
  # get  '/instructor/index' => 'instructor#index'
  resources :instructor

  # get  '/student/index' => 'student#index'
  resources :student
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  Clearance::Controller
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_and_belongs_to_many :students
    has_and_belongs_to_many :courses
    has_and_belongs_to_many :instructors
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :cohorts

end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_and_belongs_to_many :cohorts
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :cohorts
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  before_action :require_login
end

app/controllers/cohort_controller.rb
class CohortController < ApplicationController
    def index
        @cohort = Cohort.all.reverse
        @new_cohort = Cohort.new
      end

      def show
        @cohort = Cohort.find(params[:id])
        @cohort = Cohort.find(params[:name])
      end

      def create
        @temp = Cohort.create(cohort_params)

        if @temp.valid?
          flash[:notice] = "Cohort Created"
        end
        redirect_to '/cohort'
      end

      def update
        @cohort = Cohort.find(params[:id])
        @cohort.update(cohort_params)
        @cohort.save
        redirect_to '/cohort'
      end

      def destroy
        @cohort = Cohort.find(params[:id])
        @cohort.destroy
        redirect_to '/cohort'
      end

      def edit
        @cohort = Cohort.find(params[:id])
      end
      private

      def cohort_params
        params.require(:cohort).permit(:name, :sDate, :eDate)
      end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController

  def index
    @course = Course.all.reverse
    @new_course = Course.new
  end

  def show
    @course = Course.find(params[:id])
    @course = Course.cohorts(Cohort.find(params[:cohort]))
  end

  def create
    @temp = Course.create(course_params)
    @temp.cohorts<<(Cohort.find(params[:cohort]))
    if @temp.valid?
      flash[:notice] = "Course Created"
    end
    redirect_to '/course'
  end

  def update
    @course = Course.find(params[:id])
    @course.update(course_params)
    @course.save
    redirect_to '/course'
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to '/course'
  end

  def edit
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:name, :hours)
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :require_login, except: [:index]
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
    def index
        @instructor = Instructor.all.reverse
        @new_instructor = Instructor.new
      end

      def show
        @instructor = Instructor.find(params[:id])
        @instructor = Instructor.cohorts(Cohort.find(params[:cohort]))
      end

      def create
        @temp = Instructor.create(instructor_params)
        @temp.cohorts<<(Cohort.find(params[:cohort]))

        if @temp.valid?
          flash[:notice] = "Instructor Created"
        end
        redirect_to '/instructor'
      end

      def update
        @instructor = Instructor.find(params[:id])
        @instructor.update(instructor_params)
        @instructor.save
        redirect_to '/instructor'
      end

      def destroy
        @instructor = Instructor.find(params[:id])
        @instructor.destroy
        redirect_to '/instructor'
      end

      def edit
        @instructor = Instructor.find(params[:id])
      end
      private

      def instructor_params
        params.require(:instructor).permit(:fName, :lName, :age, :salary, :education)
      end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def index
        @student = Student.all.reverse
        @new_student = Student.new
      end

      def show
        @student = Student.find(params[:id])
        @student = Student.cohorts(Cohort.find(params[:cohort]))
      end

      def create
        @temp = Student.create(student_params)
        @temp.cohorts<<(Cohort.find(params[:cohort]))
        if @temp.valid?
          flash[:notice] = "Student Created"
        end
        redirect_to '/student'
      end

      def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        @student.save
        redirect_to '/student'
      end

      def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to '/student'
      end

      def edit
        @student = Student.find(params[:id])
      end
      private

      def student_params
        params.require(:student).permit(:fName, :lName, :age, :education)
      end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cohort/edit.html.erb
<%= form_for @cohort  do |c| %>
<div class="ui form">
 <h4 class="ui dividing header">Edit Cohort: <%= @cohort.name %></h4>
   <div class='field'>
    <label>Cohort</label>
    <%= c.text_field :name %>
   </div>
   <div class="field">
     <label> Duration(Start Date/End Date)</label>
   <div class="two fields">
   <div class="field">
     <%= c.text_field :sDate %>
   </div>
   <div class="field">
     <%= c.text_field :eDate %>
   </div>
  </div>
</div>
<button class="ui button" type='<%= c.submit %>'>Update</button>
  <% end %>

app/views/cohort/index.html.erb
<%= form_for @new_cohort, url: cohort_index_path, html: {class: "cohort_form"} do |i| %>
  <div class="ui form">
    <h4 class="ui dividing header">Create Cohort</h4>
    <div class="field">
      <label>Cohort</label>
      <%= i.text_field :name %>
    </div>
    <div class="field">
      <label> Duration(Start Date/End Date) </label>
    <div class="two fields">
      <div class="field">
        <%= i.text_field :sDate %>
      </div>
      <div class="field">
        <%= i.text_field :eDate %>
      </div>
    </div>
</div>
  <br>
  <button class="ui green button" type='<%= i.submit %>'>Create</button>
  <br>
  <br>
</form>

<% end %>

<div>
 <h4 class="ui dividing header">Cohorts</h4>
  <table class="ui celled table">
    <thead>
    <tr><th> Cohort </th>
    <th>Start</th>
    <th>End</th>
    <th></th>
    <th></th>
    </tr></thead>
  <tbody>
  <% @cohort.each do |i| %>
    <tr>
      <td data-label="Cohort"><%= i.name %></td>
      <td data-label="Start"><%= i.sDate %></td>
      <td data-label="End"><%= i.eDate %></td>
      <td data-label=""><%= link_to  "EDIT", edit_cohort_path(@cohort) %></td>
      <td data-label=""><%= link_to "DELETE", '/cohort/' + i.id.to_s, method: :delete, class: "btn" %></td>
    </tr>
  <% end %>
</div>

app/views/course/edit.html.erb
<%= form_for @course  do |c| %>
<div class="ui form">
   <h4 class="ui dividing header">Edit Course: <%= @course.name %></h4>
   <div class='field'>
     <label> Course Name</label>
    <%= c.text_field :name %>
</div>
   <div class='field'>
    <label> Course Hours</label>
    <%= c.text_field :hours %>
   </div>
    <br>
   <button class="ui button" type='<%= c.submit %>'>Update</button>
  <% end %>

app/views/course/index.html.erb
<%= form_for @new_course, url: course_index_path, html: {class: "course_form"} do |f| %>
    <div class="ui form">
   <h4 class="ui dividing header">Create Course</h4>
     <div class='field'>
        <div class="field">
            <div class="field">
            <label> Course Name </label>
            <%= f.text_field :name %>
            </div>
            <div class="field">
            <label> Course Hours</label>
            <%= f.text_field :hours %>
            </div>
            <div class="field">
          <label> Cohort </label>
          <%= (select_tag "cohort", options_from_collection_for_select(Cohort.all, "id", "name"))%>
        </div>
        <br>
        <button class="ui green button" type='<%= f.submit %>'>Create</button>
      </div>
    </div>
    <% end %>
    <br>

<div>
   <h4 class="ui dividing header">Courses</h4>
  <table class="ui celled table">
    <thead>
      <tr><th> Course Name</th>
      <th>Course Length</th>
      <th> Cohort </th>
      <th></th>
      <th></th>
      </tr></thead>
      <tbody>
        <% @course.each do |course| %>
          <tr>
          <td data-label="Course Name"><%= course.name %></td>
          <td data-label="Course Length"> <%= course.hours %> Hours</td>
          <td data-label="Cohort"><%= course.cohorts.first.name %></td>
          <td data-label=""><%= link_to  "EDIT", edit_course_path(course) %></td>
          <td data-label=""><%= link_to "DELETE", '/course/' + course.id.to_s, method: :delete, class: "btn" %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/home/home.html.erb
<h3>Home page</h3>

app/views/instructor/edit.html.erb
<%= form_for @instructor  do |c| %>
  <div class="ui form">
    <h4 class="ui dividing header">Edit Instructor: <%= @instructor.fName %> <%= @instructor.lName %></h4>
    <div class='field'>
      <label> First Name</label>
      <%= c.text_field :fName %>
    </div>
    <div class='field'>
      <label> Last Hours</label>
      <%= c.text_field :lName %>
    </div>
    <div class='field'>
      <label> Age </label>
      <%= c.text_field :age %>
    </div>
    <div class='field'>
      <label> Salary </label>
      <%= c.text_field :salary %>
    </div>
    <div class='field'>
      <label> Education </label>
      <%= c.text_field :education %>
    </div>
    <br>
    <button class="ui button" type='<%= c.submit %>'>Update</button>
    <br>
    <br>
  <% end %>

app/views/instructor/index.html.erb
<%= form_for @new_instructor, url: instructor_index_path, html: {class: "instructor_form"} do |i| %>
  <div class="ui form">
    <h4 class="ui dividing header"> Create Instructor</h4>
    <div class='field'>
      <label> First Name </label>
      <%= i.text_field :fName %>
    </div>
    <div class='field'>
    <label> Last Name </label>
    <%= i.text_field :lName %>
    </div>
    <div class='field'>
    <label> Age</label>
    <%= i.text_field :age %>
    </div>
    <div class='field'>
    <label> Salary </label>
    <%= i.text_field :salary %>
    </div>
    <div class='field'>
    <label> Education </label>
    <%= i.text_field :education %>
    </div>
    <div class="field">
          <label> Cohort</label>
          <%= (select_tag "cohort", options_from_collection_for_select(Cohort.all, "id", "name"))%>
        </div>
    <br>
    <button class="ui green button" type='<%= i.submit %>'>Create</button>
    <br>
    <br>
<% end %>

<div>
<h4 class="ui dividing header">Instructors</h4>
  <table class="ui celled table">
    <thead>
    <tr><th> First Name </th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Salary</th>
    <th>Education</th>
    <th> Cohort </th>
    <th></th>
    <th></th>
    </tr></thead>
  <tbody>
    <% @instructor.each do |i| %>
      <tr>
        <td data-label="First Name"><%= i.fName %></td>
        <td data-label="Last Name"><%= i.lName %></td>
        <td data-label="Age"><%= i.age %> </td>
        <td data-label="Salary"><%= i.salary %> </td>
        <td data-label="Education"><%= i.education %> </td>
        <td data-label="Cohort"><%= i.cohorts.first.name %></td>
        <td data-label="""><%= link_to  "EDIT", edit_instructor_path(@instructor) %></td>
        <td data-label=""><%= link_to "DELETE", '/instructor/' + i.id.to_s, method: :delete, class: "btn" %></td>
      </tr>
    <% end %>
  </div>

app/views/layouts/_nav.html.erb
<% if signed_in? %>

  <div class='right menu'>
      <a class="item">
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
      </a>
  </div>
      <% else %>
      <a class="item">
      <%= link_to 'Sign in', sign_in_path %>
      </a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PamelaSPanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
    <div class="ui secondary pointing menu">
    <%= render "layouts/nav" %>
    </div>

      <div class="ui grid">
      <div class="two wide column" class='col'>
      <div class="ui vertical pointing menu" class="vertically fitted item">
      <a class='item' href='/'>Home</a>
      <a class='item' href='/cohort'>Cohort</a>
      <a class='item' href='/instructor'>Instructor</a>
      <a class='item' href='/student'>Student</a>
      <a class='item' href='/course'>Course</a>
      </div>
      </div>
      <div class="fourteen wide stretched column">
      <div class="ui segment">
    <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      </div>
      <%= yield %>
      </div>
      </div>
      </div>



      <script src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
  </body>
</html>

app/views/student/edit.html.erb
<%= form_for @student do |c| %>
  <div class="ui form">
   <h4 class="ui dividing header">Edit Student: <%= @student.fName %> <%= @student.lName %></h4>
   <div class='field'>
    <label> Student First Name</label>
   </div>
    <%= c.text_field :fName %>
   <div class='field'>
    <label> Student Last Name</label>
    <%= c.text_field :lName %>
    </div>
   <div class='field'>
    <label> Age</label>
    <%= c.text_field :age %>
    </div>
   <div class='field'>
    <label> Education </label>
    <%= c.text_field :education %>
    </div>
    <br>
    <button class="ui button" type='<%= c.submit %>'>Update</button>

  <% end %>

app/views/student/index.html.erb
<%= form_for @new_student, url: student_index_path, html: {class: "student_form"} do |i| %>
  <div class="ui form">
   <h4 class="ui dividing header">Create Student</h4>
     <div class='field'>
        <div class="field">
          <label> First Name </label>
          <%= i.text_field :fName %>
        </div>
        <div class="field">
          <label> Last Name </label>
          <%= i.text_field :lName %>
        </div>
        <div class="field">
          <label> Age</label>
          <%= i.text_field :age %>
        </div>
        <div class="field">
          <label> Education </label>
          <%= i.text_field :education %>
        </div>
        <div class="field">
          <label> Cohort </label>
          <%= (select_tag "cohort", options_from_collection_for_select(Cohort.all, "id", "name"))%>
        </div>
        <br>
        <button class="ui green button" type='<%= i.submit %>'>Create</button>
        <br>
        <br>
      </div>
    </div>
<% end %>

<div>
   <h4 class="ui dividing header">Students</h4>
    <table class="ui celled table">
      <thead>
      <tr><th> First Name </th>
      <th> Last Name </th>
      <th> Age </th>
      <th> Education </th>
      <th> Cohort </th>
      <th></th>
      <th></th>
      </tr></thead>
      <tbody>
        <% @student.each do |i| %>
          <tr>
          <td data-label="First Name"><%= i.fName %></td>
          <td data-label="Last Name"><%= i.lName %></td>
          <td data-label="Age"><%= i.age %></td>
          <td data-label="Education"><%= i.education %></td>
          <td data-label="Cohort"><%= i.cohorts.first.name %></td>
          <td data-label=""><%= link_to  "EDIT", edit_student_path(@student) %></td>
          <td data-label=""><%= link_to "DELETE", '/student/' + i.id.to_s, method: :delete, class: "btn" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username, type: 'text' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>